name: Firebase Continuous Deployment
'on':
  push:
    branches:
      - arielchernis-patch-1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
version: v1.0
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Integ
    dependencies: []
    task:
      jobs:
        - name: 'Job #1'
          commands:
            - '--npm ci'
            - '--npm test'
            - '--npm run lint -- --fix'
